### ISSUE TITLE
Add support to delete project deploy keys (and other resources)

### ISSUE THREAD

**Issue by seboudry** [gdubicki/gitlabform#193]
Hi!

Delete is only implemented for a few resources.
For my usage it lacks for project deploy keys.
But other resource might benefit for global delete support.

**Comment by gdubicki** [comment]
Implemented for the deploy keys in [v2.10.0](https://github.com/gdubicki/gitlabform/releases/tag/v2.10.0), released today, @seboudry. Let me know if it works for you!

**Comment by gdubicki** [comment]
Closing as it's implemented, please reopen if you find any issues with this feature.
