### ISSUE TITLE
Applying pipeline schedules is not working

### ISSUE THREAD

**Issue by mjuraszek92** [gdubicki/gitlabform#361]
**Describe the bug**

Seems that recently there were changes in GitLab that affected current way of applying pipeline schedules.

The flow of applying pipeline schedules is following:
1. [Update pipeline schedule](https://github.com/gdubicki/gitlabform/blob/35334c8bfbaee25aea90ed3c973004bd0f0bdfab/gitlabform/processors/project/schedules_processor.py#L38)
2. [Take ownership for a schedule](https://github.com/gdubicki/gitlabform/blob/35334c8bfbaee25aea90ed3c973004bd0f0bdfab/gitlabform/processors/project/schedules_processor.py#L43)

The problem is that currently if a user performing an action is already an owner of the schedule then the point 2 ends up with error: 
`{"message":"403 Forbidden"}`

The behaviour can be easily verified in GitLab by hitting [the API](https://docs.gitlab.com/ee/api/pipeline_schedules.html#take-ownership-of-a-pipeline-schedule) two times in a row with the same user token.

**GitLabForm version**

2.10.1

**GitLab version**

14.9.4-ee

**Comment by jocado** [comment]
Confirmed here as well: `14.9.4-ee`

**Comment by jocado** [comment]
Looking at the changes, perhaps it's related to this one:

https://gitlab.com/gitlab-org/gitlab-foss/blob/master/CHANGELOG.md#14101-2022-04-29
> * Prevent maintainers from editing PipelineSchedule (merge request)

**Comment by gdubicki** [comment]
Thanks for reporting!

Probably this is also the reason the tests have failed today in https://github.com/gdubicki/gitlabform/runs/6318302269?check_suite_focus=true ...

**Comment by gdubicki** [comment]
I have just released v2.11.0b4 with the above workaround. A final release will be done after the weekend.

**Comment by gdubicki** [comment]
The workaround is now in a final release [v2.11.0](https://github.com/gdubicki/gitlabform/releases/tag/v2.11.0).

**Comment by gdubicki** [comment]
We should find/report the issue to GitLab.

**Comment by jocado** [comment]
Thanks or the quick fix :+1:
